name: Terraform-Infra Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v6.0.1

    - name: Show folder structure
      run: |
          pwd
          ls -l
          ls -l Enviroment-Infra || true

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.2
      with:
        terraform_version: 1.14.3

    - name: Terraform Init
      working-directory: Enviroment-Infra/dev
      run: terraform init

    - name: Terraform Plan (Target RG)
      working-directory: Enviroment-Infra/dev
      run: terraform plan -var-file="terraform.tfvars"
      env:
        TF_LOG: DEBUG

    # - name: Terraform plan
    #   working-directory: Enviroment-Infra/dev
    #   run: terraform plan

      
    
      
    
    
