name: Terraform-Infra Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v6.0.1

    - name: Show folder structure
      run: |
          pwd
          ls -l
          ls -l Enviroment-Infra || true

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.2
      with:
        terraform_version: 1.14.3

    - name: Terraform Init
      working-directory: Enviroment-Infra/dev
      run: terraform init

    - name: Terraform Plan
      working-directory: Enviroment-Infra/dev
      run: terraform plan \
          -var="resource_group=my-rg" \
          -var="virtual_network=my-vnet" \
          -var="subnet=my-subnet" \
          -var="bastion=my-bastion" \
          -var="sql_server=my-sql-server" \
          -var="sql_database=my-sql-db" \
          -var="storage_account=mystorageacct" \
          -var="storage_container=tfstate" \
          -var="public_ip=my-public-ip" \
          -var="key_vault=my-key-vault"


    # - name: Terraform plan
    #   working-directory: Enviroment-Infra/dev
    #   run: terraform plan

      
    
      
    
    
